---
- name: create group
  hosts: db
  tasks:
  - name: using group module
    group:
      name: hyc
      state: present
      gid: 2400

  - name: using user module
    ansible.builtin.user:
      name: hyc
      uid: 3400
      group: hyc
